name: build-and-push

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Frontend runner (includes .next build artifacts)
      - name: Build and push frontend:runner
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile
          target: runner
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-backend:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Prisma migrate image
      - name: Build and push prisma-migrate
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile
          target: prisma
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-prisma:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-prisma:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


