name: build-and-push

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'package.json'
            backend:
              - 'backend/**'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'package.json'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Frontend runner (includes .next build artifacts)
      - name: Build and push frontend:runner
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch'
        with:
          context: .
          file: frontend/Dockerfile
          target: runner
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Backend
      - name: Build and push backend
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch'
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-backend:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Frontend migrator (Prisma migrate deploy)
      - name: Build and push frontend:migrator
        uses: docker/build-push-action@v6
        if: steps.changes.outputs.frontend == 'true' || github.event_name == 'workflow_dispatch'
        with:
          context: .
          file: frontend/Dockerfile
          target: migrator
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend-migrator:latest
            ghcr.io/${{ github.repository_owner }}/smart-agent-frontend-migrator:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


